# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

stages:
- stage: build
  displayName: "build stage"

  jobs:
  - job:
    displayName: "build job"
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: echo Hello, world!
      displayName: 'Run a one-line script'
- stage:  test
  displayName: "test stage"
  jobs:
    - job:
      displayName: "test job"
      steps:
      - task: Docker@2
        inputs:
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'
- stage: deploy
  displayName: "deploy stage"
  jobs:
    - job:
      displayName: "deploy job"
      pool:
       vmImage: ubuntu-latest
      steps:
        - task: Docker@2
          inputs:
            command: 'buildAndPush'
            Dockerfile: '**/Dockerfile'
       




